name: Build

on:
  push:
    tags:
      - '*'

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: windows-latest    

    steps:
      - name: ACTIONS_ALLOW_UNSECURE_COMMANDS
        id: ACTIONS_ALLOW_UNSECURE_COMMANDS
        run: echo 'ACTIONS_ALLOW_UNSECURE_COMMANDS=true' >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Install WiX
        run: dotnet tool install --global wix

      - name: Restore Packages Civil3D2019Release
        run: dotnet msbuild /t:restore /p:Configuration=Civil3D2019Release

      - name: Build solution Civil3D2019Release
        run: | 
            msbuild PSUCivil3DUtils.sln /p:Configuration=Civil3D2019Release /p:TargetFramework=net47

      - name: Restore Packages Installer
        run: dotnet msbuild /t:restore /p:Configuration=Installer

      - name: Build Installer
        run: | 
            msbuild PSUCivil3DUtils.sln /p:Configuration=Installer /p:TargetFramework=net8.0-windows

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: PSUCivil3DUtils.Setup/Build/*.msi