name: Build

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: windows-2019    

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup MSBuild Path
        uses: warrenbuckley/Setup-MSBuild@v1

      - name: Restore NuGet Packages
        run: nuget restore PSUCivil3DUtils.sln

      - name: Build solution Civil 3D 2019 Debug
        run: msbuild PSUCivil3DUtils.sln /p:Configuration=Civil3D2019Debug