name: Build

on:
  push:
    tags:
      - '*'

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: windows-latest    

    steps:
      - name: ACTIONS_ALLOW_UNSECURE_COMMANDS
        id: ACTIONS_ALLOW_UNSECURE_COMMANDS
        run: echo 'ACTIONS_ALLOW_UNSECURE_COMMANDS=true' >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: dotnet restore PSUCivil3DUtils.sln -p:Configuration=Civil3D2019Debug -p:TargetFramework=net47

      - name: Build solution Civil 3D 2019 Debug
        run: | 
            msbuild PSUCivil3DUtils.sln /p:Configuration=Civil3D2019Debug /p:TargetFramework=net47

      - name: Install WiX
        run: dotnet tool install --global wix

      - name: Build installer
        run: | 
            msbuild PSUCivil3DUtils.sln /p:Configuration=Installer /p:TargetFramework=net8.0-windows