name: Build

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: windows-latest    

    steps:
      - name: ACTIONS_ALLOW_UNSECURE_COMMANDS
        id: ACTIONS_ALLOW_UNSECURE_COMMANDS
        run: echo 'ACTIONS_ALLOW_UNSECURE_COMMANDS=true' >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: 5.0.x

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
     
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Restore Packages
        run: nuget restore PSUCivil3DUtils.sln

      - name: Build solution Civil 3D 2019 Debug
        run: msbuild PSUCivil3DUtils.sln /p:Configuration=Civil3D2019Debug