name: Build

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: windows-2019    

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Build solution Civil 3D 2019 Debug
        run: dotnet build -c Civil3D2019Debug